SELECT [name]
      ,[idcode]
      ,[sex]
      ,[birthday]
      ,[location]
      ,[locationcode]
      ,[poname]
      ,[poldcode]
      ,[onechildcardcode]
      ,[childbirthday]
      ,[childsex]
      ,[paydate]
      ,[paynum]
      ,[isoldinsure]
      ,[lushi]
      ,[lushidate]
      ,[shenghe]
      ,[shengheren]
      ,[shenghedate]
      ,[shenghenoreason]
      ,[familycode]
      ,[unitname]
      ,[unitxingzhi]
      ,[username]
      ,[inputdate]
  FROM [lydxDB].[dbo].[dsznfmjlb]